### ISSUE TITLE
Instructions Unclear to "get the code into the Outlook Application"

### ISSUE THREAD

**Issue by dylan-k** [tallguyjenks/Obsidian-For-Business#14]
If you follow the installation steps carefully, you'll end up with a set of blank modules. There's a description of how to name them, but nothing about how to get the actual code into them. Is this what works instead?

1. drag one of the vb files into the panel that lists modules, etc.
2. a new module will be created that contains the script within that file
3. rename the module as needed.

**Comment by tallguyjenks** [comment]
i guess it was unclear to copy/paste but if the drag method works that's even better. the VBE is so archaic I tried to keep it as simple as possible

**Comment by dylan-k** [comment]
Yes it really is archaic. I'm still trying to figure this out, so I think instructions that are as detailed, but still simple... specific as possible would be a big help. 

If I do figure it out, would it help to do a pull request for updated info on how to do it? I noticed the wiki for this repo isn't set up yet.

**Comment by tallguyjenks** [comment]
Pull requests are welcome!

**Comment by dylan-k** [comment]
I'll do a PR but essentially the missing step for me was to do the following steps:  

- In Outlook, select File Menu >> Options >> Trust Center >> Trust Center Settings >> Macro Settings
- Then click Enable all macro (not  recommended; potentially dangerous code can run) in Macro Settings.
- Restart Outlook

There's a way to do trust certificates for scripts like these but I'm content with this simpler/riskier approach.
