### ISSUE TITLE
Initial Release Doesn't Contain Plugins

### ISSUE THREAD

**Issue by dylan-k** [tallguyjenks/Obsidian-For-Business#15]
Cloning the repo in its current state gives you a vault that includes plugins, but downloading the latest release version does not. Often the expectation is that the release would be more functional than the current state. Perhaps a new release would help?

**Comment by tallguyjenks** [comment]
if you download the vault from the repo and go into the settings you can download any missing updates, but since I can point to their release repo at https://github.com/obsidianmd/obsidian-releases its an option to point to that as a dependency
