### ISSUE TITLE
Possible to import email/calendar as Markdown instead of plain text?

### ISSUE THREAD

**Issue by namtrah** [tallguyjenks/Obsidian-For-Business#21]
# Feature request

In Joplin, someone has figured out how to send an email in markdown format to Joplin. a similar process must be possible for this plugin

## Is your feature request related to a problem? Please describe

Although the text formatting is fine, it is missing **bold**, *emphasized*, _underline_, ==highlighted==, and other text markers that I would expect in an email or calendar entry. 
## Describe the solution you'd like

Using some help from VBA and an HTML converter it is possible to convert an email/calendar to HTML. This can then be easily mutated into Markdown for simple highlighting blocks. As far as I can tell, there exists a MSOffice API to export as HTML. All that is left is to convert obvious cases to markdown.

## Describe alternatives you've considered

Using Joplin, a user has created a plugin that has this capability. His GIST is [here](https://gist.github.com/ramisedhom/0f34c5d6a8d73f0b98ac4bea2ec30be0), and the description is [here](https://discourse.joplinapp.org/t/first-trial-to-create-note-from-outlook/4822).

## Additional context

Please see the GIST and description on the Joplin Forum.

**Comment by namtrah** [comment]
Will you not support this? (bot changed to stale)

**Comment by tallguyjenks** [comment]
downloading emails to markdown is already supported by this project, its one of the pieces of functionality i added from the beginning, if its missing more detail than you'd like, adding an HTML converter for formatting then feel free to open a pull request, I'm avoiding writing any more VBA code if possible
