### ISSUE TITLE
VBA compile error: user-defined type not defined..."New RegExp"

### ISSUE THREAD

**Issue by mashean** [tallguyjenks/Obsidian-For-Business#22]
Hi - newbie here and very interested in using this tool but unfortunately can't get it to work with my outlook...

when I try to run the ExtractEmail macro, the application errors when it gets to the Function formatName function and gives me the VBA compile error as the New RegExp variable is not defined...

Looks like it's the SaveUtilities module.  Followed the instructions on how to install / double checked source to target and everything seems to check out yet getting a compile error

this is where the compile error is happening:

Dim regexJustFirstNameAndLastName As Object 
        Set regexJustFirstNameAndLastName = New RegExp
        regexJustFirstNameAndLastName.Pattern = "^\w+\s\w+$"
    If regexJustFirstNameAndLastName.Test(str) = True Then typeOfNameToClean = 1
    Set regexJustFirstNameAndLastName = Nothing

Appreciate any help you can provide.  Thank you.

**Comment by tallguyjenks** [comment]
and you completed [step 4](https://github.com/tallguyjenks/Obsidian-For-Business#installing-the-outlook-utilities)?

**Comment by mashean** [comment]
> and you completed [step 4](https://github.com/tallguyjenks/Obsidian-For-Business#installing-the-outlook-utilities)?

Hi Bryan!  thank you sir...feeling dumb right now :)  

It's working now.  Really love the concept and hugely helpful for someone who lives on Outlook and Obsidian.  Thank you!!!

**Comment by tallguyjenks** [comment]
glad it was something simple! Enjoy :)
